app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- End Navbar -->
    <div class="content">
      <div class="row">

        <div class="col-md-8">
          <div class="card card-user">
            <div class="card-header">
              <h5 class="card-title">
                  Login
              </h5>
              <p>
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Default Credentials: test / pass
                {% endif %} 
              </p>
            </div>
            <div class="card-body">

            <form role="form" method="post" action="">

                {{ form.hidden_tag() }} 

                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>Username</label>
                      <input class="form-control" placeholder="Username" type="text" name="username" value="test">
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>Password</label>
                      <input class="form-control" placeholder="Password" type="password" name="password" value="pass">
                    </div>
                  </div>
                </div>


                <div class="row">
                  <div class="col-md-6 pr-1">
                      <div class="update">
                          <button type="submit" name="login" class="btn btn-primary btn-round">Login</button> 
                          &nbsp; &nbsp; Don't have an account? <a href="{{ url_for('base_blueprint.register') }}">Register</a>
                      </div>
                  </div>
                </div>

              </form>

            </div>
          </div>
        </div>

      </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="content">
    <div class="row">

      <div class="col-md-8">
        <div class="card card-user">
          <div class="card-header">
            <h5 class="card-title">
                Register
            </h5>
            <p>
              {% if msg %}
                  {{ msg | safe }}
              {% else %}
                  Add your credentials
              {% endif %} 
            </p>
          </div>
          <div class="card-body">

            <!-- Hide the form on success -->
            {% if not success %}            
            <form role="form" method="post" action="">

                {{ form.hidden_tag() }}  

                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>Username</label>
                      {{ form.username(placeholder="Username", class="form-control") }}
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>Email</label>
                      {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>Password</label>
                      {{ form.password(placeholder="Password", class="form-control", type="password") }}
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-6 pr-1">
                      <div class="update">
                          <button type="submit" name="register" class="btn btn-primary btn-round">Register</button> 
                          &nbsp; &nbsp; Have an account? <a href="{{ url_for('base_blueprint.login') }}">Login</a>
                      </div>
                  </div>
                </div>
            </form>
            {% endif %}

          </div>
        </div>
      </div>

    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}  

app/base/templates/includes/footer.html
    <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
            <div class="row">
            <nav class="footer-nav">
                <ul>
                <li><a target="_blank" rel="sponsored noopener noreferrer" 
                       href="https://www.creative-tim.com/product/paper-dashboard-flask">Paper Dashboard Flask</a></li>
                </ul>
            </nav>
            <div class="credits ml-auto">
                <span class="copyright">
                &copy; <script>
                    document.write(new Date().getFullYear())
                </script> 
                <a target="_blank" rel="sponsored noopener noreferrer" href="https://www.creative-tim.com">Creative Tim</a> 
     - coded by <a target="_blank" rel="sponsored noopener noreferrer" href="https://appseed.us">AppSeed</a>.
                </span>
            </div>
            </div>
        </div>
    </footer>

app/base/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:;">
                Paper Dashboard Flask
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>

          {% if current_user.is_authenticated %}
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="nc-icon nc-zoom-split"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link btn-magnify" href="javascript:;">
                  <i class="nc-icon nc-layout-11"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Stats</span>
                  </p>
                </a>
              </li>
              <li class="nav-item btn-rotate dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nc-icon nc-settings-gear-65"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="/user.html">My Profile</a>
                  <a class="dropdown-item" href="{{ url_for('base_blueprint.logout') }}">Logout</a>
                </div>
              </li>
            </ul>
          </div>
          {% endif %}

        </div>
      </nav>
      <!-- End Navbar -->

app/base/templates/includes/scripts.html
  <script src="/static/assets/js/core/jquery.min.js"></script>
  <script src="/static/assets/js/core/popper.min.js"></script>
  <script src="/static/assets/js/core/bootstrap.min.js"></script>
  <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <!-- Chart JS -->
  <script src="/static/assets/js/plugins/chartjs.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="/static/assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/assets/js/paper-dashboard.js?v=2.0.1" type="text/javascript"></script>
  <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
  <script src="/static/assets/demo/demo.js"></script>

app/base/templates/includes/sidebar.html
<div class="sidebar" data-color="white" data-active-color="danger">
    <div class="logo">
      <a target="_blank" rel="sponsored noopener noreferrer" 
         href="https://www.creative-tim.com" 
         class="simple-text logo-mini">
        <div class="logo-image-small">
          <img src="/static/assets/img/logo-small.png">
        </div>
        <!-- <p>CT</p> -->
      </a>
      <a target="_blank" rel="sponsored noopener noreferrer" 
         href="https://www.creative-tim.com" class="simple-text logo-normal">
        Creative Tim
        <!-- <div class="logo-image-big">
          <img src="/static/assets/img/logo-big.png">
        </div> -->
      </a>
    </div>
    <div class="sidebar-wrapper">
      <ul class="nav">

        {% if current_user.is_authenticated %}
        <li class="{% if 'index' in segment %} active {% endif %}">
          <a href="/">
            <i class="nc-icon nc-bank"></i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item {% if 'icons' in segment %} active {% endif %}">
          <a href="/icons.html">
            <i class="nc-icon nc-diamond"></i>
            <p>Icons</p>
          </a>
        </li>
        <li class="nav-item {% if 'map' in segment %} active {% endif %}">
          <a href="/map.html">
            <i class="nc-icon nc-pin-3"></i>
            <p>Maps</p>
          </a>
        </li>
        <li class="nav-item {% if 'notifications' in segment %} active {% endif %}">
          <a href="/notifications.html">
            <i class="nc-icon nc-bell-55"></i>
            <p>Notifications</p>
          </a>
        </li>
        <li class="nav-item {% if 'user' in segment %} active {% endif %}">
          <a href="/user.html">
            <i class="nc-icon nc-single-02"></i>
            <p>User Profile</p>
          </a>
        </li>
        <li class="nav-item {% if 'tables' in segment %} active {% endif %}">
          <a href="/tables.html">
            <i class="nc-icon nc-tile-56"></i>
            <p>Table List</p>
          </a>
        </li>
        <li class="nav-item {% if 'typography' in segment %} active {% endif %}">
          <a href="/typography.html">
            <i class="nc-icon nc-caps-small"></i>
            <p>Typography</p>
          </a>
        </li>
        <li class="nav-item {% if 'login' in segment %} active {% endif %}">
          <a href="/login.html">
            <i class="nc-icon nc-circle-10"></i>
            <p>Login</p>
          </a>
        </li>
        <li class="nav-item {% if 'register' in segment %} active {% endif %}">
          <a href="/register.html">
            <i class="nc-icon nc-touch-id"></i>
            <p>Register</p>
          </a>
        </li>
        <li class="nav-item {% if 'page-404' in segment %} active {% endif %}">
          <a href="/page-404.html">
            <i class="nc-icon nc-settings-gear-65"></i>
            <p>Error 404</p>
          </a>
        </li>          
        <li>
          <a href="{{ url_for('base_blueprint.logout') }}">
            <i class="nc-icon nc-user-run"></i>
            <p>Logout</p>
          </a>
        </li>          
        <li class="active-pro">
          <a target="_blank" rel="sponsored noopener noreferrer" 
             href="https://www.creative-tim.com/templates/flask">
            <i class="nc-icon nc-spaceship"></i>
            <p>More Starters</p>
          </a>
        </li>
        {% else %}
        <li class="active">
          <a target="_blank" rel="sponsored noopener noreferrer" 
             href="https://www.creative-tim.com/templates/flask">
            <i class="nc-icon nc-spaceship"></i>
            <p>More Starters</p>
          </a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>

app/base/templates/layouts/base-fullscreen.html
<!-- NOT_IMPLEMENTED -->

app/base/templates/layouts/base.html
<!--
=========================================================
* Paper Dashboard Flask - v1.0.0
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-flask
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com / AppSeed.us

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
<!-- Anti-flicker snippet (recommended)  -->
<style>.async-hide { opacity: 0 !important} </style>
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
{'GTM-K9BGS8K':true});</script>

<!-- Analytics-Optimize Snippet -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-46172202-22', 'auto', {allowLinker: true});
ga('set', 'anonymizeIp', true);
ga('require', 'GTM-K9BGS8K');
ga('require', 'displayfeatures');
ga('require', 'linker');
ga('linker:autoLink', ["2checkout.com","avangate.com"]);
</script>
<!-- end Analytics-Optimize Snippet -->
  
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NKDMSK6');</script>
<!-- End Google Tag Manager -->
  
<!-- ************************************************************************************** -->
<!-- Creative-Tim SEO & Social content -->

<!-- Canonical SEO -->
<link rel="canonical" href="https://www.creative-tim.com/product/paper-dashboard-flask" />

<!--  Social tags      -->
<meta name="keywords" content="creative tim, flask, backend, html dashboard, html css dashboard, web dashboard, bootstrap 4 dashboard, bootstrap 4, css3 dashboard, bootstrap 4 admin, paper dashboard bootstrap 4 dashboard, frontend, responsive bootstrap 4 dashboard, paper design, paper dashboard bootstrap 4 dashboard">
<meta name="description" content="Paper Dashboard Flask is a beautiful Bootstrap 4 Admin Dashboard with a huge number of components built to fit together and look amazing.">

<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="Paper Dashboard Flask by Creative Tim">
<meta itemprop="description" content="Paper Dashboard Flask is a beautiful Bootstrap 4 Admin Dashboard with a huge number of components built to fit together and look amazing.">

<meta itemprop="image" content="https://s3.amazonaws.com/creativetim_bucket/products/385/original/paper-dashboard-flask-thumbnail.jpg">

<!-- Twitter Card data -->
<meta name="twitter:card" content="product">
<meta name="twitter:site" content="@creativetim">
<meta name="twitter:title" content="Paper Dashboard Flask by Creative Tim">

<meta name="twitter:description" content="Paper Dashboard Flask is a beautiful Bootstrap 4 Admin Dashboard with a huge number of components built to fit together and look amazing.">
<meta name="twitter:creator" content="@creativetim">
<meta name="twitter:image" content="https://s3.amazonaws.com/creativetim_bucket/products/385/original/paper-dashboard-flask-thumbnail.jpg">

<!-- Open Graph data -->
<meta property="fb:app_id" content="655968634437471">
<meta property="og:title" content="Paper Dashboard Flask by Creative Tim" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://paper-dashboard-flask.creative-tim.com/" />
<meta property="og:image" content="https://s3.amazonaws.com/creativetim_bucket/products/385/original/paper-dashboard-flask-thumbnail.jpg"/>
<meta property="og:description" content="Paper Dashboard Flask is a beautiful Bootstrap 4 Admin Dashboard with a huge number of components built to fit together and look amazing." />
<meta property="og:site_name" content="Creative Tim" />

<!-- Creative-Tim SEO & Social content -->
<!-- ************************************************************************************** -->

  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="/static/assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Paper Dashboard Flask - {% block title %}{% endblock %} | AppSeed
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="/static/assets/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/static/assets/css/paper-dashboard.css?v=2.0.1" rel="stylesheet" />
  
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/static/assets/demo/demo.css" rel="stylesheet" />

  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="">

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NKDMSK6"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->  

  <div class="wrapper ">

    {% include 'includes/sidebar.html' %}

    <div class="main-panel">

      {% include 'includes/navigation.html' %}

      {% block content %}{% endblock content %}

      {% include 'includes/footer.html' %}

    </div>
  </div>

  {% include 'includes/scripts.html' %}

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}

</body>

</html>